macro(PatchSrc arg)
	file(GLOB PatchFiles "${arg}/*.cpp")
	foreach(patch IN LISTS PatchFiles)
		string(REGEX REPLACE "${arg}" "./src" toRemove ${patch})
		file(TO_CMAKE_PATH ${toRemove} toRemovePath)
		list(REMOVE_ITEM SOURCES ${toRemovePath})
		list(APPEND SOURCES ${patch})
	endforeach()
endmacro()
